<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Library</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>preview</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<WarningsAsErrors>nullable</WarningsAsErrors>
		<DebugType Condition="'$(Configuration)' == 'Release'">none</DebugType>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>
		<PackageId>Engine4.Client</PackageId>
	</PropertyGroup>

	<!-- Includes -->
	<ItemGroup>
		<PackageReference Include="JetBrains.Annotations" Version="2025.2.4" PrivateAssets="all"/>
		<PackageReference Include="Silk.NET.GLFW" Version="2.23.0"/>
		<PackageReference Include="Silk.NET.OpenGL" Version="2.23.0"/>
		<PackageReference Include="Silk.NET.Vulkan" Version="2.23.0"/>

		<ProjectReference Include="..\Engine4\Engine4.csproj"/>

		<EmbeddedResource Include="Assets\**"/>
	</ItemGroup>
</Project>