namespace Engine4.Client.Graphics.Vulkan;

public delegate bool IsPhysicalDeviceSuitableDelegate(PhysicalGpuProperties physicalGpuProperties);
public delegate SurfaceReadyPhysicalGpu SelectGpuDelegate(SurfaceReadyPhysicalGpu[] physicalGpus);
public delegate int RateGpuSuitabilityDelegate(SurfaceReadyPhysicalGpu physicalGpu);